{
 "title": "QOR_PNR",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "WNS of path groups across stages",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT metric,floorplan,place,cts,route FROM \"{{TIME_TABLE}}\" WHERE metric like '%WNS'"
    }
   ]
  },
  {
   "title": "TNS of pathgroups across stages",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT metric,floorplan,place,cts,route FROM \"{{TIME_TABLE}}\" WHERE metric like '%TNS'"
    }
   ]
  },
  {
   "title": "FEPs across stages",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"{{TIME_TABLE}}\" WHERE metric ILIKE '%violating%';"
    }
   ]
  },
  {
   "title": "Density(%)",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH formatted_panel AS (\r\n    SELECT\r\n        CASE \r\n            WHEN metric = 'floorplan_density(%)' THEN 'floorplan'\r\n            WHEN metric = 'place_density(%)' THEN 'place'\r\n            WHEN metric = 'cts_density(%)' THEN 'cts'\r\n            WHEN metric = 'route_density(%)' THEN 'route'\r\n        END AS density_type,\r\n        value\r\n    FROM (SELECT * FROM {{RUN_TABLE}} \r\nwhere metric like '%density%')\r\n)\r\nSELECT \r\n    'Density(%)' AS parameter,\r\n    MAX(CASE WHEN density_type = 'floorplan' THEN value END) AS floorplan,\r\n    MAX(CASE WHEN density_type = 'place' THEN value END) AS place,\r\n    MAX(CASE WHEN density_type = 'cts' THEN value END) AS cts,\r\n    MAX(CASE WHEN density_type = 'route' THEN value END) AS route\r\nFROM formatted_panel;"
    }
   ]
  },
  {
   "title": "power(mW)",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 10, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "rawSql": "WITH formatted_panel AS (\r\n    SELECT\r\n        CASE \r\n            WHEN metric LIKE 'floorplan_power(%)' THEN 'floorplan'\r\n            WHEN metric LIKE 'place_power(%)' THEN 'place'\r\n            WHEN metric LIKE 'cts_power(%)' THEN 'cts'\r\n            WHEN metric LIKE 'route_power(%)' THEN 'route'\r\n        END AS stage,\r\n        CASE\r\n            WHEN metric LIKE '%(Internal)' THEN 'internal power'\r\n            WHEN metric LIKE '%(switching)' THEN 'switching power'\r\n            WHEN metric LIKE '%(leakage)' THEN 'leakage power'\r\n            WHEN metric LIKE '%(total)' THEN 'total power'\r\n        END AS power_type,\r\n        value\r\n    FROM {{RUN_TABLE}} \r\n    WHERE metric ILIKE '%power%'\r\n)\r\nSELECT \r\n    stage,\r\n    COALESCE(MAX(CASE WHEN power_type = 'internal power' THEN value END), 0) AS \"internal power\",\r\n    COALESCE(MAX(CASE WHEN power_type = 'switching power' THEN value END), 0) AS \"switching power\",\r\n    COALESCE(MAX(CASE WHEN power_type = 'leakage power' THEN value END), 0) AS \"leakage power\"\r\nFROM formatted_panel\r\nGROUP BY stage\r\nORDER BY \r\n    CASE stage \r\n        WHEN 'floorplan' THEN 1\r\n        WHEN 'place' THEN 2\r\n        WHEN 'cts' THEN 3\r\n        WHEN 'route' THEN 4\r\n    END;"
    }
   ]
  },
  {
   "title": "floorplan area",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    'floorplan' AS run,\r\n    MAX(CASE WHEN metric = 'floorplan_combo_area' THEN value END) AS combinational_area,\r\n    MAX(CASE WHEN metric = 'floorplan_buffer_area' THEN value END) AS buffer_area,\r\n    MAX(CASE WHEN metric = 'floorplan_physical_area' THEN value END) AS physical_area,\r\n    MAX(CASE WHEN metric = 'floorplan_icgs_area' THEN value END) AS icgs_area,\r\n    MAX(CASE WHEN metric = 'floorplan_latch_area' THEN value END) AS latch_area\r\nFROM \r\n    {{RUN_TABLE}}\r\nWHERE \r\n    metric ILIKE '%floorplan%area%'"
    }
   ]
  },
  {
   "title": "Place area",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    'place' AS run,\r\n    MAX(CASE WHEN metric = 'place_combo_area' THEN value END) AS combinational_area,\r\n    MAX(CASE WHEN metric = 'place_buffer_area' THEN value END) AS buffer_area,\r\n    MAX(CASE WHEN metric = 'place_physical_area' THEN value END) AS physical_area,\r\n    MAX(CASE WHEN metric = 'place_icgs_area' THEN value END) AS icgs_area,\r\n    MAX(CASE WHEN metric = 'place_latch_area' THEN value END) AS latch_area\r\nFROM \r\n    {{RUN_TABLE}}\r\nWHERE \r\n    metric ILIKE '%place%area%'"
    }
   ]
  },
  {
   "title": "cts area",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    'cts' AS run,\r\n    MAX(CASE WHEN metric = 'cts_combo_area' THEN value END) AS combinational_area,\r\n    MAX(CASE WHEN metric = 'cts_buffer_area' THEN value END) AS buffer_area,\r\n    MAX(CASE WHEN metric = 'cts_physical_area' THEN value END) AS physical_area,\r\n    MAX(CASE WHEN metric = 'cts_icgs_area' THEN value END) AS icgs_area,\r\n    MAX(CASE WHEN metric = 'cts_latch_area' THEN value END) AS latch_area\r\nFROM \r\n    {{RUN_TABLE}}\r\nWHERE \r\n    metric ILIKE '%cts%area%'"
    }
   ]
  },
  {
   "title": "route area",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    'route' AS run,\r\n    MAX(CASE WHEN metric = 'route_combo_area' THEN value END) AS combinational_area,\r\n    MAX(CASE WHEN metric = 'route_buffer_area' THEN value END) AS buffer_area,\r\n    MAX(CASE WHEN metric = 'route_physical_area' THEN value END) AS physical_area,\r\n    MAX(CASE WHEN metric = 'route_icgs_area' THEN value END) AS icgs_area,\r\n    MAX(CASE WHEN metric = 'route_latch_area' THEN value END) AS latch_area\r\nFROM \r\n    {{RUN_TABLE}}\r\nWHERE \r\n    metric ILIKE '%route%area%'"
    }
   ]
  },
  {
   "title": "OVERFLOW",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "WITH formatted_overflow AS (\r\n    SELECT\r\n        CASE \r\n            WHEN metric LIKE 'place_overflow(%)' THEN 'place'\r\n            WHEN metric LIKE 'cts_overflow(%)' THEN 'cts'\r\n        END AS stage,\r\n        CASE\r\n            WHEN metric LIKE '%(H%)' THEN 'overflow_H'\r\n            WHEN metric LIKE '%(V%)' THEN 'overflow_V'\r\n        END AS overflow_type,\r\n        value\r\n    FROM (SELECT * FROM {{RUN_TABLE}} WHERE metric ILIKE '%overflow%')\r\n)\r\nSELECT \r\n    overflow_type AS parameter,\r\n    COALESCE(MAX(CASE WHEN stage = 'place' THEN value END), 0) AS \"place\",\r\n    COALESCE(MAX(CASE WHEN stage = 'cts' THEN value END), 0) AS \"cts\"\r\nFROM formatted_overflow\r\nGROUP BY overflow_type\r\nORDER BY \r\n    CASE overflow_type \r\n        WHEN 'overflow_H' THEN 1\r\n        WHEN 'overflow_V' THEN 2\r\n    END;"
    }
   ]
  },
  {
   "title": "Hotspot",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "rawSql": "WITH formatted_panel AS (\r\n    SELECT\r\n        CASE \r\n            WHEN metric LIKE 'place_Hotspot(max)' THEN 'place'\r\n            WHEN metric LIKE 'cts_Hotspot(max)' THEN 'cts'\r\n            WHEN metric LIKE 'place_Hotspot(total)' THEN 'place'\r\n            WHEN metric LIKE 'cts_Hotspot(total)' THEN 'cts'\r\n        END AS category,\r\n        CASE\r\n            WHEN metric LIKE '%(max)' THEN 'max_hotspot'\r\n            WHEN metric LIKE '%(total)' THEN 'total_hotspot'\r\n        END AS parameter,\r\n        value\r\n    FROM (SELECT * FROM {{RUN_TABLE}} WHERE metric ILIKE '%hotspot%' AND metric NOT ILIKE 'floorplan%')\r\n)\r\nSELECT \r\n    parameter,\r\n    MAX(CASE WHEN category = 'place' THEN value END) AS place,\r\n    MAX(CASE WHEN category = 'cts' THEN value END) AS cts\r\nFROM formatted_panel\r\nGROUP BY parameter;"
    }
   ]
  },
  {
   "title": "route_instances",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    'route' AS run,\r\n    MAX(CASE WHEN metric = 'route_combinational_count' THEN value END) AS combinational_count,\r\n    MAX(CASE WHEN metric = 'route_buffer_count' THEN value END) AS buffer_count,\r\n    MAX(CASE WHEN metric = 'route_sequential_count' THEN value END) AS sequential_count,\r\n    MAX(CASE WHEN metric = 'route_macro_count' THEN value END) AS macro_count,\r\n    MAX(CASE WHEN metric = 'route_latch_count' THEN value END) AS latch_count,\r\n    MAX(CASE WHEN metric = 'route_flop_count' THEN value END) AS flop_count\r\nFROM \r\n    {{RUN_TABLE}}\r\nWHERE \r\n    metric ILIKE '%route%count%'"
    }
   ]
  },
  {
   "title": "place_instances",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    'place' AS run,\r\n    MAX(CASE WHEN metric = 'place_combinational_count' THEN value END) AS combinational_count,\r\n    MAX(CASE WHEN metric = 'place_buffer_count' THEN value END) AS buffer_count,\r\n    MAX(CASE WHEN metric = 'place_sequential_count' THEN value END) AS sequential_count,\r\n    MAX(CASE WHEN metric = 'place_macro_count' THEN value END) AS macro_count,\r\n    MAX(CASE WHEN metric = 'place_latch_count' THEN value END) AS latch_count,\r\n    MAX(CASE WHEN metric = 'place_flop_count' THEN value END) AS flop_count\r\nFROM \r\n    {{RUN_TABLE}}\r\nWHERE \r\n    metric ILIKE '%place%count%'"
    }
   ]
  },
  {
   "title": "floorplan_instances",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    'floorplan' AS run,\r\n    MAX(CASE WHEN metric = 'floorplan_combinational_count' THEN value END) AS combinational_count,\r\n    MAX(CASE WHEN metric = 'floorplan_buffer_count' THEN value END) AS buffer_count,\r\n    MAX(CASE WHEN metric = 'floorplan_sequential_count' THEN value END) AS sequential_count,\r\n    MAX(CASE WHEN metric = 'floorplan_macro_count' THEN value END) AS macro_count,\r\n    MAX(CASE WHEN metric = 'floorplan_latch_count' THEN value END) AS latch_count,\r\n    MAX(CASE WHEN metric = 'floorplan_flop_count' THEN value END) AS flop_count\r\nFROM \r\n    {{RUN_TABLE}}\r\nWHERE \r\n    metric ILIKE '%floorplan%count%'"
    }
   ]
  },
  {
   "title": "cts_instances",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    'cts' AS run,\r\n    MAX(CASE WHEN metric = 'cts_combinational_count' THEN value END) AS combinational_count,\r\n    MAX(CASE WHEN metric = 'cts_buffer_count' THEN value END) AS buffer_count,\r\n    MAX(CASE WHEN metric = 'cts_sequential_count' THEN value END) AS sequential_count,\r\n    MAX(CASE WHEN metric = 'cts_macro_count' THEN value END) AS macro_count,\r\n    MAX(CASE WHEN metric = 'cts_latch_count' THEN value END) AS latch_count,\r\n    MAX(CASE WHEN metric = 'cts_flop_count' THEN value END) AS flop_count\r\nFROM \r\n    {{RUN_TABLE}}\r\nWHERE \r\n    metric ILIKE '%cts%count%'"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM {{RUN_TABLE}}\r\nWHERE metric ILIKE '%time%'"
    }
   ]
  },
  {
   "title": "Timing Data",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT metric, floorplan, place, cts, route FROM {{TIME_TABLE}}"
    }
   ]
  },
  {
   "title": "QoR data",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "WITH formatted_qor AS (\r\n    SELECT\r\n        CASE \r\n            WHEN metric LIKE 'floorplan_%' THEN 'floorplan'\r\n            WHEN metric LIKE 'place_%' THEN 'place'\r\n            WHEN metric LIKE 'cts_%' THEN 'cts'\r\n            WHEN metric LIKE 'route_%' THEN 'route'\r\n        END AS stage,\r\n        REGEXP_REPLACE(metric, '^(floorplan_|place_|cts_|route_)', '') AS parameter,\r\n        value\r\n    FROM (SELECT * FROM {{RUN_TABLE}})\r\n)\r\nSELECT \r\n    parameter,\r\n    COALESCE(MAX(CASE WHEN stage = 'floorplan' THEN value END), 0) AS \"floorplan\",\r\n    COALESCE(MAX(CASE WHEN stage = 'place' THEN value END), 0) AS \"place\",\r\n    COALESCE(MAX(CASE WHEN stage = 'cts' THEN value END), 0) AS \"cts\",\r\n    COALESCE(MAX(CASE WHEN stage = 'route' THEN value END), 0) AS \"route\"\r\nFROM formatted_qor\r\nGROUP BY parameter\r\nORDER BY parameter;"
    }
   ]
  },
  {
   "title": "DRC at route",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 72 },
   "targets": [
    { "rawSql": "SELECT * FROM {{DRC_TABLE}}" }
   ]
  }
 ]
}