{
 "title": "Run Comparison Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "run_number", "query": "1" },
   { "name": "DATASOURCE_UID", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "WNS comparison run{{RUN_NUMBER}} vs run{{NEXT_RUN_NUMBER}}",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    *\nFROM (\n    SELECT \n        'Run {{RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'place_setup_WNS' THEN value END) AS place_setup_WNS,\n        MAX(CASE WHEN metric = 'cts_setup_WNS' THEN value END) AS cts_setup_WNS,\n        MAX(CASE WHEN metric = 'route_setup_WNS' THEN value END) AS route_setup_WNS\n    FROM {{RUN_TABLE}} \n    WHERE metric ILIKE '%WNS'\n\n    UNION ALL\n\n    SELECT \n        'Run {{NEXT_RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'place_setup_WNS' THEN value END) AS place_setup_WNS,\n        MAX(CASE WHEN metric = 'cts_setup_WNS' THEN value END) AS cts_setup_WNS,\n        MAX(CASE WHEN metric = 'route_setup_WNS' THEN value END) AS route_setup_WNS\n    FROM {{NEXT_RUN_TABLE}} \n    WHERE metric ILIKE '%WNS'\n) AS subquery;"
    }
   ]
  },
  {
   "title": "TNS comparison run{{RUN_NUMBER}} vs run{{NEXT_RUN_NUMBER}}",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    *\nFROM (\n    SELECT \n        'Run {{RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'place_setup_TNS' THEN value END) AS place_setup_TNS,\n        MAX(CASE WHEN metric = 'cts_setup_TNS' THEN value END) AS cts_setup_TNS,\n        MAX(CASE WHEN metric = 'route_setup_TNS' THEN value END) AS route_setup_TNS\n    FROM {{RUN_TABLE}} \n    WHERE metric ILIKE '%TNS'\n\n    UNION ALL\n\n    SELECT \n        'Run {{NEXT_RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'place_setup_TNS' THEN value END) AS place_setup_TNS,\n        MAX(CASE WHEN metric = 'cts_setup_TNS' THEN value END) AS cts_setup_TNS,\n        MAX(CASE WHEN metric = 'route_setup_TNS' THEN value END) AS route_setup_TNS\n    FROM {{NEXT_RUN_TABLE}} \n    WHERE metric ILIKE '%TNS'\n) AS subquery;"
    }
   ]
  },
  {
   "title": "FEPS comparison run{{RUN_NUMBER}} vs run{{NEXT_RUN_NUMBER}}",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    *\nFROM (\n    SELECT \n        'Run {{RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'place_setup_FEPS' THEN value END) AS place_setup_FEPS,\n        MAX(CASE WHEN metric = 'cts_setup_FEPS' THEN value END) AS cts_setup_FEPS,\n        MAX(CASE WHEN metric = 'route_setup_FEPS' THEN value END) AS route_setup_FEPS\n    FROM {{RUN_TABLE}} \n    WHERE metric ILIKE '%FEPS'\n\n    UNION ALL\n\n    SELECT \n        'Run {{NEXT_RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'place_setup_FEPS' THEN value END) AS place_setup_FEPS,\n        MAX(CASE WHEN metric = 'cts_setup_FEPS' THEN value END) AS cts_setup_FEPS,\n        MAX(CASE WHEN metric = 'route_setup_FEPS' THEN value END) AS route_setup_FEPS\n    FROM {{NEXT_RUN_TABLE}} \n    WHERE metric ILIKE '%FEPS'\n) AS subquery;"
    }
   ]
  },
  {
   "title": "density across stages run{{NEXT_RUN_NUMBER}}",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \n    'Run {{NEXT_RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'floorplan_density(%)' THEN value END) AS floorplan_density,\n    MAX(CASE WHEN metric = 'place_density(%)' THEN value END) AS place_density,\n    MAX(CASE WHEN metric = 'cts_density(%)' THEN value END) AS cts_density,\n    MAX(CASE WHEN metric = 'route_density(%)' THEN value END) AS route_density\nFROM \n    {{NEXT_RUN_TABLE}};"
    }
   ]
  },
  {
   "title": "density across stages run{{RUN_NUMBER}}",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \n    'Run {{RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'floorplan_density(%)' THEN value END) AS floorplan_density,\n    MAX(CASE WHEN metric = 'place_density(%)' THEN value END) AS place_density,\n    MAX(CASE WHEN metric = 'cts_density(%)' THEN value END) AS cts_density,\n    MAX(CASE WHEN metric = 'route_density(%)' THEN value END) AS route_density\nFROM \n    {{RUN_TABLE}};"
    }
   ]
  },
  {
   "title": "power across runs {{RUN_NUMBER}} vs {{NEXT_RUN_NUMBER}}",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \n    'place_Run {{RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'place_power_Internal' THEN value END) AS power_Internal,\n    MAX(CASE WHEN metric = 'place_power_switching' THEN value END) AS power_switching,\n    MAX(CASE WHEN metric = 'place_power_leakage' THEN value END) AS power_leakage\nFROM {{RUN_POWER_TABLE}}\nWHERE metric ILIKE '%power%'\n\nUNION ALL\n\nSELECT \n    'place_Run {{NEXT_RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'place_power_Internal' THEN value END) AS power_Internal,\n    MAX(CASE WHEN metric = 'place_power_switching' THEN value END) AS power_switching,\n    MAX(CASE WHEN metric = 'place_power_leakage' THEN value END) AS power_leakage\nFROM {{NEXT_RUN_POWER_TABLE}}\nWHERE metric ILIKE '%power%'\n\nUNION ALL\n\nSELECT \n    'cts_Run {{RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'cts_power_Internal' THEN value END) AS power_Internal,\n    MAX(CASE WHEN metric = 'cts_power_switching' THEN value END) AS power_switching,\n    MAX(CASE WHEN metric = 'cts_power_leakage' THEN value END) AS power_leakage\nFROM {{RUN_POWER_TABLE}}\nWHERE metric ILIKE '%power%'\n\nUNION ALL\n\nSELECT \n    'cts_Run {{NEXT_RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'cts_power_Internal' THEN value END) AS power_Internal,\n    MAX(CASE WHEN metric = 'cts_power_switching' THEN value END) AS power_switching,\n    MAX(CASE WHEN metric = 'cts_power_leakage' THEN value END) AS power_leakage\nFROM {{NEXT_RUN_POWER_TABLE}}\nWHERE metric ILIKE '%power%'\n\nUNION ALL\n\nSELECT \n    'route_Run {{RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'route_power_Internal' THEN value END) AS power_Internal,\n    MAX(CASE WHEN metric = 'route_power_switching' THEN value END) AS power_switching,\n    MAX(CASE WHEN metric = 'route_power_leakage' THEN value END) AS power_leakage\nFROM {{RUN_POWER_TABLE}}\nWHERE metric ILIKE '%power%'\n\nUNION ALL\n\nSELECT \n    'route_Run {{NEXT_RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'route_power_Internal' THEN value END) AS power_Internal,\n    MAX(CASE WHEN metric = 'route_power_switching' THEN value END) AS power_switching,\n    MAX(CASE WHEN metric = 'route_power_leakage' THEN value END) AS power_leakage\nFROM {{NEXT_RUN_POWER_TABLE}}\nWHERE metric ILIKE '%power%';"
    }
   ]
  },
  {
   "title": "area for run{{RUN_NUMBER}} across stages",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \n    'floorplan_Run {{RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'floorplan_combo_area' THEN value END) AS combinational_area,\n    MAX(CASE WHEN metric = 'floorplan_buffer_area' THEN value END) AS buffer_area,\n    MAX(CASE WHEN metric = 'floorplan_physical_area' THEN value END) AS physical_area,\n    MAX(CASE WHEN metric = 'floorplan_icgs_area' THEN value END) AS icgs_area,\n    MAX(CASE WHEN metric = 'floorplan_latch_area' THEN value END) AS latch_area\nFROM \n    {{RUN_TABLE}} \nWHERE \n    metric ILIKE '%floorplan%area%'\n\nUNION ALL\n\nSELECT \n    'place_Run {{RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'place_combo_area' THEN value END) AS combinational_area,\n    MAX(CASE WHEN metric = 'place_buffer_area' THEN value END) AS buffer_area,\n    MAX(CASE WHEN metric = 'place_physical_area' THEN value END) AS physical_area,\n    MAX(CASE WHEN metric = 'place_icgs_area' THEN value END) AS icgs_area,\n    MAX(CASE WHEN metric = 'place_latch_area' THEN value END) AS latch_area\nFROM \n    {{RUN_TABLE}} \nWHERE \n    metric ILIKE '%place%area%'\n\nUNION ALL\n\nSELECT \n    'cts_Run {{RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'cts_combo_area' THEN value END) AS combinational_area,\n    MAX(CASE WHEN metric = 'cts_buffer_area' THEN value END) AS buffer_area,\n    MAX(CASE WHEN metric = 'cts_physical_area' THEN value END) AS physical_area,\n    MAX(CASE WHEN metric = 'cts_icgs_area' THEN value END) AS icgs_area,\n    MAX(CASE WHEN metric = 'cts_latch_area' THEN value END) AS latch_area\nFROM \n    {{RUN_TABLE}}\nWHERE \n    metric ILIKE '%cts%area%'\n\nUNION ALL\n\nSELECT \n    'route_Run {{RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'route_combo_area' THEN value END) AS combinational_area,\n    MAX(CASE WHEN metric = 'route_buffer_area' THEN value END) AS buffer_area,\n    MAX(CASE WHEN metric = 'route_physical_area' THEN value END) AS physical_area,\n    MAX(CASE WHEN metric = 'route_icgs_area' THEN value END) AS icgs_area,\n    MAX(CASE WHEN metric = 'route_latch_area' THEN value END) AS latch_area\nFROM \n    {{RUN_TABLE}} \nWHERE \n    metric ILIKE '%route%area%';"
    }
   ]
  },
  {
   "title": "area for run{{NEXT_RUN_NUMBER}} across stages",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \n    'floorplan_Run {{NEXT_RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'floorplan_combo_area' THEN value END) AS combinational_area,\n    MAX(CASE WHEN metric = 'floorplan_buffer_area' THEN value END) AS buffer_area,\n    MAX(CASE WHEN metric = 'floorplan_physical_area' THEN value END) AS physical_area,\n    MAX(CASE WHEN metric = 'floorplan_icgs_area' THEN value END) AS icgs_area,\n    MAX(CASE WHEN metric = 'floorplan_latch_area' THEN value END) AS latch_area\nFROM \n    {{NEXT_RUN_TABLE}} \nWHERE \n    metric ILIKE '%floorplan%area%'\n\nUNION ALL\n\nSELECT \n    'place_Run {{NEXT_RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'place_combo_area' THEN value END) AS combinational_area,\n    MAX(CASE WHEN metric = 'place_buffer_area' THEN value END) AS buffer_area,\n    MAX(CASE WHEN metric = 'place_physical_area' THEN value END) AS physical_area,\n    MAX(CASE WHEN metric = 'place_icgs_area' THEN value END) AS icgs_area,\n    MAX(CASE WHEN metric = 'place_latch_area' THEN value END) AS latch_area\nFROM \n    {{NEXT_RUN_TABLE}}\nWHERE \n    metric ILIKE '%place%area%'\n\nUNION ALL\n\nSELECT \n    'cts_Run {{NEXT_RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'cts_combo_area' THEN value END) AS combinational_area,\n    MAX(CASE WHEN metric = 'cts_buffer_area' THEN value END) AS buffer_area,\n    MAX(CASE WHEN metric = 'cts_physical_area' THEN value END) AS physical_area,\n    MAX(CASE WHEN metric = 'cts_icgs_area' THEN value END) AS icgs_area,\n    MAX(CASE WHEN metric = 'cts_latch_area' THEN value END) AS latch_area\nFROM \n    {{NEXT_RUN_TABLE}}\nWHERE \n    metric ILIKE '%cts%area%'\n\nUNION ALL\n\nSELECT \n    'route_Run {{NEXT_RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'route_combo_area' THEN value END) AS combinational_area,\n    MAX(CASE WHEN metric = 'route_buffer_area' THEN value END) AS buffer_area,\n    MAX(CASE WHEN metric = 'route_physical_area' THEN value END) AS physical_area,\n    MAX(CASE WHEN metric = 'route_icgs_area' THEN value END) AS icgs_area,\n    MAX(CASE WHEN metric = 'route_latch_area' THEN value END) AS latch_area\nFROM \n    {{NEXT_RUN_TABLE}} \nWHERE \n    metric ILIKE '%route%area%';"
    }
   ]
  },
  {
   "title": "instance count for run{{RUN_NUMBER}}",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \n    'floorplan_Run {{RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'floorplan_combinational_count' THEN value END) AS combinational_count,\n    MAX(CASE WHEN metric = 'floorplan_buffer_count' THEN value END) AS buffer_count,\n    MAX(CASE WHEN metric = 'floorplan_latch_count' THEN value END) AS latch_count,\n    MAX(CASE WHEN metric = 'floorplan_flop_count' THEN value END) AS flop_count\nFROM \n    {{RUN_TABLE}} \nWHERE \n    metric ILIKE '%floorplan%count%'\n\nUNION ALL\n\nSELECT \n    'place_Run {{RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'place_combinational_count' THEN value END) AS combinational_count,\n    MAX(CASE WHEN metric = 'place_buffer_count' THEN value END) AS buffer_count,\n    MAX(CASE WHEN metric = 'place_latch_count' THEN value END) AS latch_count,\n    MAX(CASE WHEN metric = 'place_flop_count' THEN value END) AS flop_count\nFROM \n    {{RUN_TABLE}}\nWHERE \n    metric ILIKE '%place%count%'\n\nUNION ALL\n\nSELECT \n    'cts_Run {{RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'cts_combinational_count' THEN value END) AS combinational_count,\n    MAX(CASE WHEN metric = 'cts_buffer_count' THEN value END) AS buffer_count,\n    MAX(CASE WHEN metric = 'cts_latch_count' THEN value END) AS latch_count,\n    MAX(CASE WHEN metric = 'cts_flop_count' THEN value END) AS flop_count\nFROM \n    {{RUN_TABLE}}\nWHERE \n    metric ILIKE '%cts%count%'\n\nUNION ALL\n\nSELECT \n    'route_Run {{RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'route_combinational_count' THEN value END) AS combinational_count,\n    MAX(CASE WHEN metric = 'route_buffer_count' THEN value END) AS buffer_count,\n    MAX(CASE WHEN metric = 'route_latch_count' THEN value END) AS latch_count,\n    MAX(CASE WHEN metric = 'route_flop_count' THEN value END) AS flop_count\nFROM \n    {{RUN_TABLE}}\nWHERE \n    metric ILIKE '%route%count%';"
    }
   ]
  },
  {
   "title": "instance count for run{{NEXT_RUN_NUMBER}} across stages",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \n    'floorplan_Run {{NEXT_RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'floorplan_combinational_count' THEN value END) AS combinational_count,\n    MAX(CASE WHEN metric = 'floorplan_buffer_count' THEN value END) AS buffer_count,\n    MAX(CASE WHEN metric = 'floorplan_latch_count' THEN value END) AS latch_count,\n    MAX(CASE WHEN metric = 'floorplan_flop_count' THEN value END) AS flop_count\nFROM \n    {{NEXT_RUN_TABLE}}\nWHERE \n    metric ILIKE '%floorplan%count%'\n\nUNION ALL\n\nSELECT \n    'place_Run {{NEXT_RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'place_combinational_count' THEN value END) AS combinational_count,\n    MAX(CASE WHEN metric = 'place_buffer_count' THEN value END) AS buffer_count,\n    MAX(CASE WHEN metric = 'place_latch_count' THEN value END) AS latch_count,\n    MAX(CASE WHEN metric = 'place_flop_count' THEN value END) AS flop_count\nFROM \n    {{NEXT_RUN_TABLE}}\nWHERE \n    metric ILIKE '%place%count%'\n\nUNION ALL\n\nSELECT \n    'cts_Run {{NEXT_RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'cts_combinational_count' THEN value END) AS combinational_count,\n    MAX(CASE WHEN metric = 'cts_buffer_count' THEN value END) AS buffer_count,\n    MAX(CASE WHEN metric = 'cts_latch_count' THEN value END) AS latch_count,\n    MAX(CASE WHEN metric = 'cts_flop_count' THEN value END) AS flop_count\nFROM \n    {{NEXT_RUN_TABLE}}\nWHERE \n    metric ILIKE '%cts%count%'\n\nUNION ALL\n\nSELECT \n    'route_Run {{NEXT_RUN_NUMBER}}' AS run,\n    MAX(CASE WHEN metric = 'route_combinational_count' THEN value END) AS combinational_count,\n    MAX(CASE WHEN metric = 'route_buffer_count' THEN value END) AS buffer_count,\n    MAX(CASE WHEN metric = 'route_latch_count' THEN value END) AS latch_count,\n    MAX(CASE WHEN metric = 'route_flop_count' THEN value END) AS flop_count\nFROM \n    {{NEXT_RUN_TABLE}}\nWHERE \n    metric ILIKE '%route%count%';"
    }
   ]
  },
  {
   "title": "max_hotspot across runs {{RUN_NUMBER}} vs {{NEXT_RUN_NUMBER}}",
   "type": "xychart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT \n    ROW_NUMBER() OVER () AS run_no, \n    *\nFROM (\n    SELECT \n        'Run {{RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'floorplan_Hotspot(max)' THEN CAST(value AS FLOAT) END) AS floorplan_hotspot_max,\n        MAX(CASE WHEN metric = 'place_Hotspot(max)' THEN CAST(value AS FLOAT) END) AS place_hotspot_max,\n        MAX(CASE WHEN metric = 'cts_Hotspot(max)' THEN CAST(value AS FLOAT) END) AS cts_hotspot_max\n    FROM \n        {{RUN_TABLE}}\n\n    UNION ALL\n\n    SELECT \n        'Run {{NEXT_RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'floorplan_Hotspot(max)' THEN CAST(value AS FLOAT) END) AS floorplan_hotspot_max,\n        MAX(CASE WHEN metric = 'place_Hotspot(max)' THEN CAST(value AS FLOAT) END) AS place_hotspot_max,\n        MAX(CASE WHEN metric = 'cts_Hotspot(max)' THEN CAST(value AS FLOAT) END) AS cts_hotspot_max\n    FROM \n        {{NEXT_RUN_TABLE}}\n) AS subquery;"
    }
   ]
  },
  {
   "title": "total_hotspot across runs {{RUN_NUMBER}} vs {{NEXT_RUN_NUMBER}}",
   "type": "xychart",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT \n    ROW_NUMBER() OVER () AS run_no, \n    *\nFROM (\n    SELECT \n        'Run {{RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'floorplan_Hotspot(total)' THEN CAST(value AS FLOAT) END) AS floorplan_hotspot_total,\n        MAX(CASE WHEN metric = 'place_Hotspot(total)' THEN CAST(value AS FLOAT) END) AS place_hotspot_total,\n        MAX(CASE WHEN metric = 'cts_Hotspot(total)' THEN CAST(value AS FLOAT) END) AS cts_hotspot_total\n    FROM \n        {{RUN_TABLE}}\n\n    UNION ALL\n\n    SELECT \n        'Run {{NEXT_RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'floorplan_Hotspot(total)' THEN CAST(value AS FLOAT) END) AS floorplan_hotspot_total,\n        MAX(CASE WHEN metric = 'place_Hotspot(total)' THEN CAST(value AS FLOAT) END) AS place_hotspot_total,\n        MAX(CASE WHEN metric = 'cts_Hotspot(total)' THEN CAST(value AS FLOAT) END) AS cts_hotspot_total\n    FROM \n        {{NEXT_RUN_TABLE}}\n) AS subquery;"
    }
   ]
  },
  {
   "title": "horizontal congestion across runs {{RUN_NUMBER}} vs {{NEXT_RUN_NUMBER}}(overflow(%))",
   "type": "xychart",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT \n    ROW_NUMBER() OVER () AS run_no, \n    *\nFROM (\n    SELECT \n        'Run {{RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'floorplan_overflow(H(%))' THEN CAST(value AS FLOAT) END) AS floorplan_overflow_h,\n        MAX(CASE WHEN metric = 'place_overflow(H(%))' THEN CAST(value AS FLOAT) END) AS place_overflow_h,\n        MAX(CASE WHEN metric = 'cts_overflow(H(%))' THEN CAST(value AS FLOAT) END) AS cts_overflow_h\n    FROM \n        {{RUN_TABLE}} \n\n    UNION ALL\n\n    SELECT \n        'Run {{NEXT_RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'floorplan_overflow(H(%))' THEN CAST(value AS FLOAT) END) AS floorplan_overflow_h,\n        MAX(CASE WHEN metric = 'place_overflow(H(%))' THEN CAST(value AS FLOAT) END) AS place_overflow_h,\n        MAX(CASE WHEN metric = 'cts_overflow(H(%))' THEN CAST(value AS FLOAT) END) AS cts_overflow_h\n    FROM \n        {{NEXT_RUN_TABLE}}\n) AS subquery;"
    }
   ]
  },
  {
   "title": "vertical congestion across runs {{RUN_NUMBER}} vs {{NEXT_RUN_NUMBER}}(overflow(%))",
   "type": "xychart",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT \n    ROW_NUMBER() OVER () AS run_no, \n    *\nFROM (\n    SELECT \n        'Run {{RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'floorplan_overflow(V(%))' THEN CAST(value AS FLOAT) END) AS floorplan_overflow_v,\n        MAX(CASE WHEN metric = 'place_overflow(V(%))' THEN CAST(value AS FLOAT) END) AS place_overflow_v,\n        MAX(CASE WHEN metric = 'cts_overflow(V(%))' THEN CAST(value AS FLOAT) END) AS cts_overflow_v\n    FROM \n        {{RUN_TABLE}} \n\n    UNION ALL\n\n    SELECT \n        'Run {{NEXT_RUN_NUMBER}}' AS run,\n        MAX(CASE WHEN metric = 'floorplan_overflow(V(%))' THEN CAST(value AS FLOAT) END) AS floorplan_overflow_v,\n        MAX(CASE WHEN metric = 'place_overflow(V(%))' THEN CAST(value AS FLOAT) END) AS place_overflow_v,\n        MAX(CASE WHEN metric = 'cts_overflow(V(%))' THEN CAST(value AS FLOAT) END) AS cts_overflow_v\n    FROM \n        {{NEXT_RUN_TABLE}}\n) AS subquery;"
    }
   ]
  },
  {
   "title": "runtime of run{{RUN_NUMBER}}",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM {{RUN_TABLE}} WHERE metric ILIKE '%time%';"
    }
   ]
  },
  {
   "title": "runtime of run{{NEXT_RUN_NUMBER}}",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM {{NEXT_RUN_TABLE}} WHERE metric ILIKE '%time%';"
    }
   ]
  },
  {
   "title": "run comparison data {{RUN_NUMBER}} vs {{NEXT_RUN_NUMBER}}",
   "type": "table",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT \n    metric,\n    MAX(CASE WHEN run = 'Run {{RUN_NUMBER}}' THEN value END) AS run{{RUN_NUMBER}}_value,\n    MAX(CASE WHEN run = 'Run {{NEXT_RUN_NUMBER}}' THEN value END) AS run{{NEXT_RUN_NUMBER}}_value\nFROM (\n    SELECT \n        metric,\n        value,\n        'Run {{RUN_NUMBER}}' AS run\n    FROM \n        {{RUN_COMPARE_TABLE}} \n\n    UNION ALL\n    \n    SELECT \n        metric,\n        value,\n        'Run {{NEXT_RUN_NUMBER}}' AS run\n    FROM \n        {{NEXT_RUN_COMPARE_TABLE}} \n) AS combined_data\nGROUP BY \n    metric\nORDER BY \n    metric;"
    }
   ]
  },
  {
   "title": "drc_run{{RUN_NUMBER}}",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "rawSql": "SELECT * FROM {{DRC_TABLE}} LIMIT 50;"
    }
   ]
  },
  {
   "title": "drc_run{{NEXT_RUN_NUMBER}}",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "rawSql": "SELECT * FROM {{NEXT_DRC_TABLE}} LIMIT 50;"
    }
   ]
  }
 ]
}