{
 "title": "slack Comparison",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CTS slack ",
   "type": "histogram",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 10 },
   "targets": [
    {
     "rawSql": "SELECT endpoint, CAST(slack AS DOUBLE PRECISION) AS slack FROM {{CTS_TABLE}} LIMIT 1000;"
    }
   ]
  },
  {
   "title": "Route slack ",
   "type": "histogram",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 10 },
   "targets": [
    {
     "rawSql": "SELECT endpoint, CAST(slack AS DOUBLE PRECISION) AS slack FROM {{ROUTE_TABLE}} LIMIT 1000;"
    }
   ]
  },
  {
   "title": "CTS Table",
   "type": "table",
   "gridPos": { "x": 0, "y": 10, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT endpoint, CAST(slack AS DOUBLE PRECISION) AS slack FROM {{CTS_TABLE}} ORDER BY combodelay DESC LIMIT 1000;"
    }
   ]
  },
  {
   "title": "Route Table",
   "type": "table",
   "gridPos": { "x": 12, "y": 10, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT endpoint, CAST(slack AS DOUBLE PRECISION) AS slack FROM {{ROUTE_TABLE}} ORDER BY combodelay DESC LIMIT 1000;"
    }
   ]
  }
 ]
}