{
 "title": "template_1738346838",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Delay",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT beginpoint, bufdelay, combodelay, netdelay, seqdelay, totaldelay \r\nFROM PLACEHOLDER_TABLE_NAME \r\n\r\nLIMIT 50;"
    }
   ]
  },
  {
   "title": "Delay_pie",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT beginpoint,bufdelay,combodelay,netdelay,invdelay,seqdelay,totaldelay FROM PLACEHOLDER_TABLE_NAME LIMIT 50 "
    }
   ]
  },
  {
   "title": "slack",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT beginpoint,slack FROM PLACEHOLDER_TABLE_NAME order by slack asc LIMIT 50 "
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT beginpoint,fanout,libsetup,required,portcount,wirelength,load FROM PLACEHOLDER_TABLE_NAME LIMIT 50 "
    }
   ]
  },
  {
   "title": "count",
   "type": "histogram",
   "description": "count",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT beginpoint,bufcount,combocount,invcount,instcount,netcount,portcount FROM PLACEHOLDER_TABLE_NAME  LIMIT 50 "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT beginpoint,bufcount,combocount,fanout,instcount,netcount,seqcount,invcount,netdelay,load FROM PLACEHOLDER_TABLE_NAME LIMIT 50 "
    }
   ]
  },
  {
   "title": "All_Data_View",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT * FROM PLACEHOLDER_TABLE_NAME LIMIT 50 "
    }
   ]
  }
 ]
}